language: elixir
elixir:
  - 1.0.5
otp_release:
  - 17.5
  - 18.0
before_script:
  - MIX_ENV=test mix do deps.get
script:
  - MIX_ENV=test mix test --no-start
after_script:
  - MIX_ENV=test mix coveralls.travis
services:
  - redis-server
sudo: false # to use container based infrastructure at Travis
